<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cx.Core\Cx.Core.csproj" />
    <ProjectReference Include="..\Cx.Ai\Cx.Ai.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\cx.settings.json" Link="cx.settings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
