<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="OllamaSharp" />
    <PackageReference Include="Anthropic" />
    <PackageReference Include="Google.GenAI" />
    <PackageReference Include="ModelContextProtocol.Core" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cx.Core\Cx.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Cx.Tests" />
  </ItemGroup>
</Project>
